---
title: "Final Project Instruction"
author: "Dr. Wang"
date: "March 31, 2022"
output: 
  html_document:
    theme: yeti
---

### Congratulations! 

You've learned so much in the past months!!! Now is the time to construct your very own final project. 

- You can work on the project all by yourself, or in a team with **no more than 3** students.

- You are going to choose a topic, collect the data, and apply what you've learned.

- Use **at least two different models** in the project. [Two sample test, ANOVA, linear regression, categorical data Analysis]

- The final project will have two components: **poster presentation** and **written report**. 

- Start early! Find your teammates, choose a topic, find the data, have a “plan” and submit it by Monday April 11. Note: You will submit a informal proposal(data description, research question, model, etc.) along with the data on Notebowl.




# Poster Presentation (**20 pts ,April 28-29 and May 02.**)

You are going to create a poster for your project. In a poster, you are going to clearly state the research hypothesis, describe the data source, explain the analytical models and make the conclusion. A poster should have titles, headlines, bullets, graphs, acknowledgments and references. A poster should be short, clean, effective and conclusive. Please see the following instructions on how to make a nice poster.

[How to Create a Research Poster](https://guides.nyu.edu/posters)

[How to make an academic poster in powerpoint](https://www.youtube.com/watch?v=_WnhoIbfcoM)

[Some examples from Cornell University](https://www.behance.net/gallery/30160927/Scientific-Posters)

You are going to have a pdf file for the poster. You and your teammates will give a short presentation on it (target length: 8 min). Each and every team member must show up and present his/her own part. Poster presentation will be on April 28-29 and May 02. After the presentation, you will upload the poster to Notebowl.




# Written Report (**80 pts, Due 11:59pm Dec 21.**)


In the final project paper, you should including all the details(graphs, results,...). For instance, in the poster people may say "all model assumptions are satisfied", in the paper, each assumption should be carefully discussed with solid supportive evidences like p-values or graphs. 







