---
title: "Math 135 Exam 2"
output: 
  html_document:
    toc: true
    toc_depth: 3
    theme: yeti
    df_print: paged
  
  
---

```{r setup, include=FALSE}

#---------- RSTUDIO STARTER V 2.0  --------------#
#                    -Prepared with care by  AM ;D
                
                                                                          
knitr::opts_chunk$set(echo = TRUE, 
                      message = FALSE, 
                      warning = FALSE)      
library(tidyverse)                
library(ggthemes)                    

theme_set(theme_tufte() +                                     
  theme(text=element_text(family="sans")))  

#------------------------------------------------#
```

For credit, show clear and coherent work on all problems.


1) Compute the following:

$$\frac{d}{dx}2^\left({\frac{x^2}{\cos(x)}}\right)$$


2) Compute the following:

$$\frac{d}{dx}\cos(\cos(\cos(2x)))$$


3)  Find the equation of the tangent line for the curve below at the point $(1,0)$:

$$x^2+y^2+\cos(xy^3)=x+1$$




4) If $f(x)=2x^3-3$, compute 

$$\frac{d}{dx}\left.f^{-1}(x)\right|_{x=-1}$$


5) Identify the horizontal and vertical asymptotes of 

$$f(x)=\frac{2(x-1)(x+1)(x+3)}{(x-2)(x+1)(x+4)}$$



6) Compute

$$\lim_{x\rightarrow 0^+}x\ln(x)$$




7) Suppose that for a given function $f(x)$, its second derivative is

$$f''(x)=(x-3)(x+2)$$

- If $f(x)$ has critical points at $x=-4$, $x=0$, and $x=3$, find the locations ($x-$coordinates) of all local mins and maxes for $f(x)$.  Justify with the second derivative test.


8) A water tank is shaped like a big ice cream cone, with a circular top.  The radius of the circle on top is 5ft.  The height of the cone is 8ft.  

- If water is pouring into the tank at a rate of 2 cubic ft per minute, at what level is the height of the water raising when the current height is 3ft?  You may use the fact that the volume of a cone is $V=\frac{1}{3}\pi r^2h$

9) What point on the line $y=3x-1$ comes as close as possible to the point $(-1,4)$? Give its coordinate


