---
title: "DA 101 Lec 19"
author: "Your Name"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document:
    toc: true
    toc_depth: 3
    code_folding: show
    theme: simplex
    df_print: paged
  
---

```{r setup, include=FALSE}

#---------- RSTUDIO STARTER V 2.0  --------------#
#                    -Prepared with care by  AM ;D
                
                                                                          
knitr::opts_chunk$set(echo = TRUE, 
                      message = FALSE, 
                      warning = FALSE)      
library(tidyverse)                
library(ggthemes)                    

theme_set(theme_tufte() +                                     
  theme(text=element_text(family="sans")))  

#------------------------------------------------#
```


## Intro

```{r}

msaData <- read_csv("Stanford_MSA_Database.csv")



msaData %>% select(-Description, -`Day of Week`, -`Shooter Name`, -`Type of Gun - Detailed`, -`Targeted Victim/s - Detailed`, -`Possible Motive - Detailed`, -`History of Mental Illness - Detailed`, -starts_with("Data "), -Notes) -> msaDataTrunc


```

```{r}
library(rworldmap)
library(ggmap)

states <- map_data(map="state")


msaDataTrunc %>% rename(region = State) -> msaDataTrunc

library(openintro)     ## students will need to install this library

msaDataTrunc$region %>% 
  tolower() ->
  msaDataTrunc$region

states <- left_join(states, count(msaDataTrunc, region))

ggplot() +
  geom_map(data=states, 
           map=states, 
           aes(map_id=region, x=long, y=lat, fill=n)) +
  scale_fill_gradient(low="purple", high="orange", guide="colourbar")+
  labs(x = "Longitude", y="Latitude", title ="Cloropleth Map of Mass Shootings")



```

```{r}
us <- c(left = -126, bottom = 24.5, right = -66, top = 50)
myMap <- get_stamenmap(us, zoom=5, maptype="toner-lite")



ggmap(myMap) +
  geom_density2d(data=msaDataTrunc, aes(x=Longitude, y=Latitude), size=0.3)+
  stat_density2d(data=msaDataTrunc, 
                 aes(x=Longitude, y=Latitude, fill=..level.., alpha=..level..),
                 size=0.01, bins=20,
             	    geom="polygon") +
  scale_fill_gradient(low = "blue", high = "orange") +
  scale_alpha(range = c(0, 0.3), guide = FALSE)+
  labs(x="Longitude", y="Latitude", title="Heat Map of US Mass Shooting Fatalities")+geom_point(data = msaDataTrunc, aes(x=Longitude, y=Latitude), alpha=.5, size=1)



us <- c(left = -92, bottom = 22, right = -70, top = 47)
myMap <- get_stamenmap(us, zoom=5, maptype="toner-lite")


ggmap(myMap) +
  geom_density2d(data=msaDataTrunc, aes(x=Longitude, y=Latitude), size=0.3)+
  stat_density2d(data=msaDataTrunc, 
                 aes(x=Longitude, y=Latitude, fill=..level.., alpha=..level..),
                 size=0.01, bins=16,
             	    geom="polygon") +
  scale_fill_gradient(low = "blue", high = "orange") +
  scale_alpha(range = c(0, 0.3), guide = FALSE)+
  labs(x="Longitude", y="Latitude", title="Heat Map of Socal Mass Shooting Fatalities")+geom_point(data = msaDataTrunc, aes(x=Longitude, y=Latitude), alpha=.5)+
  theme(legend.position = "none")



```

