---
title: "Math 120 Lec 05"
author: "[Your Name Here!]"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document:
    toc: true
    toc_depth: 4
    code_folding: show
    theme: simplex
  
---

```{r setup, include=FALSE}
###########################################################################
################# DON'T DELETE THIS PART!!!!!##############################
###########################################################################
                                                                          #
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)      #
                                                                          #
library(tidyverse)           #The tidyverse has all of our data tools     #
library(ggthemes)            #ggthemes makes our graphs look nicer        #
                                                                          # 
theme_set(                                #this sets the theme for all    #
  theme_tufte() +                         #plots that we make             #
  theme(text=element_text(family="sans"))                                 #
  )                                                                       #
                                                                          #
                                                                          #
                                                                          #
### Below is where you read and store your data.                          #
                                                                          #
#youShouldRenameThis <- read_csv("death penalty data.csv")
                                                                          #
                                                                          #
                                                                          #
############# ^ ################################# ^ #######################
############# | ## DON'T DELETE THIS PART!!!!!### | #######################
############# | ################################# | #######################
```

##  Reading Discussion: Sampling Strategies

Can you imagine/invent a scenario?

## Sampling 

### Populations, Samples, and Inference

- **Population**:  All individuals of interest. (Too big!)
- **Sample**:  A subset that we can actually work with.
- **Statistical Inference**:  

### Robust Statistics

A statistic is **robust** if it's not not affected by skew/outliers.


#### Example: `mpg` displacement




### Observational Studies vs Experiments

**Key difference**: In an experiment, we *apply a treatment*.

- Think: 
  - A survey is ...
  - A medical trial is  ...


   

#### Ex: 1.22a




## Sampling Problems

We need to be sure our sample is "good"!

### "Representative" or not?

In order to be useful, we need some assurance that the sample is "similar to" the population.  

In mathese:  Hope our statistics are close to the true population parameter.


###  Bias, Nonresponse Bias, and Confounding Variables

- **Sample Bias**:  Some indivuals ("cases") more likely to be observed.
- **Nonresponse Bias**:  Some individuals excluded from sample selection process.
- **Confounding Variables**:  Other variables that might affect response variable.

#### Ex:  1,22c, 1.24 and 1.26




## Sampling Strategies

### Simple Random Sample (SRS)

- Every member of the population is equally likely to be sampled.
- Best kind!

### Stratified

- Break into similar "strata", SRS within each strata.
- Ensure all groups represented.
- Example strata: gender, age, income, education, etc.

### Clustered

- Break into "clusters", randomloy select which clusters used, sample everyone in chosen clusters.
- Useful for sample over large geographic area
- Example clusters: city block, county

### Multistage

- First cluster, then SRS within selected clusters.  Nice, but expensive.

### Ex: 1.19, 1.23