---
title: "Math 120 Lecture Journal"
author: "Ali Miller"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document:
    theme: yeti
    toc: true
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

*Note: All section numbers come from our text, [Openintro Statistics]("https://www.openintro.org/stat/textbook.php?stat_book=os").  


## Week 11

### Monday 11/11

- Left tail, right tail, and two-sided tests
- Computing p-vals for two-sided tests


##  Week 10

### Fri 11/08

- Prof Miller talked about canyons for a while.  
  - Something something self reliance, something something Bloom's taxonomy
- Example of hyp test
- Connection between hyp tests and confidence intervals
- Making conclusions in hyp tests based on confidence intervals

### Thurs 11/07

- Lab 5

### Wed 11/06

- Looking at the 4 steps in detail
- Examples of hyp tests.


### Monday 11/04

- Introduction to hypothesis tests
- Four steps:
  1) Hypotheses
  2) Test statistic
  3) p-value
  4) Conclusion


## Week 9

### Friday 11/01

- Meaning of "confidence"
- Planning ahead for sample size and MOE

### Thursday 10/31

- Practicing CIs on datasets

### Wednesday 10/30

- Lab 5

### Monday 10/28

- Intro to confidence intervals 
  - Basic idea (normal distro centered around point estimate)
  - Finding critical value $z^*$
  - Computing intervals with the formula:  $$ \hat{p} \pm z^* \sqrt{\frac{\hat{p}(1-\hat{p})}{n}}$$


## Week 8

### Friday 10/25

- Practice problems with samplign distributions
  - Using `pnorm` to find probabilities for sample results.

### Thursday 10/24

- Sampling Distributions Continued
  - Distribution for $\hat{p}$
  - center, spread for $\hat{p}$
  - Success/failure condition (deciding if $n$ is "large enough")

### Wednesday 10/23

- Normal Dist review
  - `pnorm()`
- Sampling Distributions
  - Example:  Sampling distro for $\bar{x}$ with $n=2$ from Dice Distro
  

### Monday 10/21

- Lab 4


## Week 7 (Fall Break)


### Monday 10/14
- Pracitce with `pnorm`


## Week 6

### Friday 10/11

- Comparing Normal Distros:  Z-Scores
  - ACT/SAT example
- Empirical Rule
- Verifying Normality of data
- Normal distributions are -everywhere!-

### Thursday 10/10

- Lab 4 Begins

### Wednesday 10/09

- Important property of cts RVs: endpoints
- The Normal Distro
  - Properties
  - Examples

### Monday 10/07

- Reading: Name That Distro!
- Continuous Distros
  - Cts vs Discrete
  - P(X==a)
  - How cts pdfs and cdfs work
- The Uniform Distro
  - Examples

  

## Week 5

### Friday 10/04

- Special activity: Name That Distro!

### Thursday 10/03

- Poisson Distro
  - Properties
  - Using pdf and cdf
  - Examples

### Wednesday 10/02

- Binomial Examples
  - Sampling DU students
  - Multiple Choice Exam
  - Baby Tiger Snakes
- Mean and variance of binomial
  - Interpreting examples above


### Monday 9/30

- Special Discrete Distribution:  **Binomial Dist**
- Example: tossing three coins
- Binomial Random Variables
- The distribution
  - pdf
  - cdf



## Week 4

### Friday 9/27
- Variance of a discrete distro
  - Definition
  - Single dice example
  - Sum of two dice example

### Thurs 9/26
- Expected Value of a discrete distro
  - Definition
  - Single dice example
  - Sum of two dice example

### Wednedsay 9/25

- Lab 3

### Monday 9/23

- Discrete Random Variables
- Discrete Probability Distributions
- Simple Example:  Rolling a single dice
- Medium Example:  Sum of two dice




## Week 3

### Friday 9/21
- Lab

### Thursday 9/20

- Understanding Contingency (Two-Way) Tables
- Making Contingency Tables in R
- Mutually Exclusive/Disjoint Events
  - The "or" rule for mutually exclusive events
- Conditional Probability
- Independent Events
  - The "and" rule for independent events
- Checking Independence

### Wednesday 9/19


- Reading Discussion: What is Randomness?
- Final Considerations about Linear Models (for now)
  - Use numerical variables
  - Correlation $\neq$ causation!
  - Spurrious Correlations
- Randomness
  - In-class Demo: Gambling!!!


### Monday 9/16

- Interpreting residualal plots (continued)
- Examining the effects of outliers 
- Examples!

## Week 2

### Friday 9/13

Lab - Linear Regression

### Thursday 9/12

- Least Squares Equation
  - The equation
  - Uniqueness
  - Idea behind deriving it
  - Using `lm` in R
  - Making predictions
  - Meaning of the coefficients
- Residuals
  - Meaning (math and graphical)
  - Example: `mpg` data
  - Interpreting Residual Plots
- Effects of Outliers

  
### Wednesday 9/11

- Reading Discussion: Linear Regression
- Intro to Correlation and Linear Regression
  - Examples:  `mpg` data
  - Key qualities of a relationship
- Linear correlation coefficient $r$,
  - What $r$ is
  - What $r$ measures
  - Example: 8.8 on page 314

  

 
### Monday 9/9

- Reading Discussion: Sampling Strategies
- Sampling 
  - Populations, Samples, and Inference
  - Robust Statistics
  - Example: `mpg` displacement
  - Observational Studies vs Experiments
  - Ex: 1.22a
- Sampling Problems
  -  Bias, Nonresponse Bias, and Confounding Variables
     - Ex:  1,22c, 1.24 and 1.26
- Sampling Strategies
  - Simple Random Sample (SRS)
  - Stratified
  - Clustered
  - Multistage
  - Ex: 1.19, 1.23
 
## Week 1 
    
### Friday 9/6

- Reading discussion:  how did lab go?  Thoughts? Questions? Insights?
- Box Plots and Scatterplots In-Depth
  - Parts of a Boxplot
  - Weird-looking boxplot examples!
  - When scatterplots make sense (and when they don't)
  
    
    
### Thursday 9/5

- Lab day!  Still begin with reading discussion.
- You'll have the whole hour to work.
- **Start your lab before class**, so that you can get help!


### Wednesday 9/4
- Textbook:  Chapter 2
- Imporant numerical summaries of data (statistics):
  - mean, median (measures of **center**)
  - standard deviation, iqr (measures of **spread**)
- Important visual summaries of data (graphs):
  - Histograms, boxplots, Scatterplots, Violin Plots
- Describing distributions
  - Understanding **shape**, **center**, and **spread**.
  

### Monday 9/2

- Reading Discussion:  Lab 1
  - Understand the codebook?
  - What variables are you interested in?
- Exploratory Data Analysis (EDA) in RStudio:
  -`filter()`
  - Types of visuals, stats
  - How to facet by color (`fill= ...`), and what can go wrong.


## Week 0

### Friday 8/30

- Reading Discussion: Data Types 
  - Continuous, Discrete, Ordinal, Nominal
  - Identify which is which
- Intro to RStudio
  - Start a new RMarkdown file
- Important new code:
   - `read_csv()`
   - `<-` 
   - `qplot()`
   
   
   
### Thursday 8/29

- Intro to class, syllabus day