---
title: "Math 120 Lab 6: Categorical Inference"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document:
    toc: false
    toc_depth: 3
    code_folding: show
    theme: yeti
    df_print: paged
  
---

```{r setup, include=FALSE}
###########################################################################
################# DON'T DELETE THIS PART!!!!!##############################
###########################################################################
                                                                          #
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)      #
                                                                          #
library(tidyverse)           #The tidyverse has all of our data tools     #
library(ggthemes)            #ggthemes makes our graphs look nicer        #
                                                                          # 
theme_set(                                #this sets the theme for all    #
  theme_tufte() +                         #plots that we make             #
  theme(text=element_text(family="sans"))                                 #
  )                                                                       #
                                                                          #
                                                                          #
                                                                          #
### Below is where you read and store your data.                          #
                                                                          #
youShouldRenameThis <- read_csv("death penalty data.csv")
                                                                          #
                                                                          #
                                                                          #
############# ^ ################################# ^ #######################
############# | ## DON'T DELETE THIS PART!!!!!### | #######################
############# | ################################# | #######################
```



## The Data 

The dataset for this lab [(download here)](https://millera2.github.io/Data/political-data.csv) contains the responses from 3,906 American users of the "Show of Hands" app for iPhone and Android.  On the app, users answer questions about a variety of socioeconomic questions ranging from gender, income, and political party to more esoteric questions like "Does life have a purpose?" or "Are you left-handed?".  

## The Lab

In this lab, we'll be using all we know about inference to study political party affiliation of users of the Show of Hands app.  You might find it helpful to refer to your code from Lab 5; there are similarities here.  For all inference tools used (i.e., hyp tests and CIs), be sure to include full discussion of the process, detailed interpretation of the results, and any concerns about the validity of the conclusion one might have.  Use this lab as an opportunity to demonstrate your understanding of hyp tests and CIs in a practical setting.

We'll consider this dataset to be a sample of the larger population of Show of Hands users.  Your job will to be to write up a polished analysis (with intro and conclusion) that addresses the following issues:

### Part 1: The Whole Sample

- What can you say about the political party for the entire dataset?  What are the sample proportions for Democrats and Republicans; which party is in the majority in this sample?  
- Use a hypothesis test to see if there's statistically significant evidence that a higher proportion of users belong to the majority party (i.e., greater than 50%).  Carefully explain all steps, and the implications of your conclusion.  What conditions are required for the sample in order to perform such a hypothesis test; are these conditions met by your sample?
- Also, construct and interpret a confidence interval for the proportion of users that belong to the majority party.  Does this CI agree with the results of your test?  Why or why not?  What is the margin of error for that confidence interval?  How large would our sample have needed to be in order to get estmate the proportion to within 1% (i.e., MOE of 1%?)


### Part 2:  Educational Subgroup Analysis

- Now, pick two educational groups that you'd like to compare.  What are the majority parties in those two groups?  For each group, use CIs to estimate the proportion who belong to the majority party.  What conclusions do you make about the two groups based on these estimates?
- Conduct a 2-sample Z test for proportions to investigate evidence for a difference between the two groups.  Carefully explain all steps and conclusions.
- Explain carefully what Type I and Type II errors would mean in this case.  Which one is worse, do you think?  Ceratinly, you could argue either way here: your reasoning is the important part, not which error you think is worse.  Based on your reasoning, what adjustments might you make to the hyp test?  
- Construct a CI to estimate the difference in proportion of party affiliation between the two groups.  Discuss the conclusion, the connection to the hyp test above, and the margin of error.





## Deadline and Grading

This lab (both .rmd and **polished .html**) is due **Thurs, Nov 21st at 11:59pm**.   **I'll charge a 20% late fee per day late.**  

I will assign grades on this project ”holistically”, not using a scoring sheet where each item is worth a certain number of points.

- **B**: A ”B” project is very well done. It should have sound analysis, use appropriate statistical tools, support analysis with the appropriate graphs and other visual aids, and be a well-written document.

- **C**: A ”C” project is solid, but usually lacking in one of the areas listed above. 

- **D/F**: Projects below a C are severely deficient in the basic criteria or have failed to complete the assignment.

- **A**: An ”A” project is truly above ordinary; it has exceptional qualities that make it stand out distinctly. An ”A” project is not the default grade.
  - Does the project fulfill the requirements of the assignment?
  - Does this report have a ”thesis” or ”story” that is the focus? Does the rest of the report support the thesis?
  - Does the report use the subject matter from this unit appropriately? Are there tools being used in the wrong way? Is there an obvious tool that might have been used but was overlooked?
  - Are the graphics factually correct? Are they formatted well? Do they give the first visual impression that is supportive of the thesis/story of the report, or do they indicate a different story?
  - Is the report well-written? Is there good organization of ideas? Is the story/thesis communicated clearly? Is the analysis grounded in reasonable use of statistics? Is the paper free of mechanical and grammatical errors?
  - Does the report provide the right context for the target audience? Is the right information provided? Have the right assumptions been made about what the audience knows or does not know?
  
  
