---
title: "Math 120 HW"
author: "Your Name"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document:
    toc: true
    toc_depth: 1
    code_folding: show
    theme: yeti
    df_print: paged
  
  
---

```{r setup, include=FALSE}

#---------- RSTUDIO STARTER V 2.0  --------------#
#                    -Prepared with care by  AM ;D
                
                                                                          
knitr::opts_chunk$set(echo = TRUE, 
                      message = FALSE, 
                      warning = FALSE)      
library(tidyverse)                
library(ggthemes)                    

theme_set(theme_tufte() +                                     
  theme(text=element_text(family="sans")))  

#------------------------------------------------#
```

# HW 6 - Inference on The Counted

Independent British newspaper The Guarian conducted a study in 2015 and 2016 to record data on all Americans killed by police in the United States (amazingly, no US agency tracks this data).  The project is called "The Counted", and you can peruse the results at [The Guardian's Website](https://www.theguardian.com/us-news/ng-interactive/2015/jun/01/the-counted-police-killings-us-database)

For this lab, you can find the two datasets in our usual shared folder for data -- find links on our GitHub homepage as always.

In the usual format (polished Google Docs report exported to pdf), answer the following questions about the data.

1) For each dataset, make a pivot table showing the frequencies broken down by the variables `raceethnicity` and `armed`.  Paste those pivot tables into your report.

2)  In 2015-2016, about 13.5% of all Americans were African-American.  Using the data above, find out what percent of people killed by police are black.  For each year (seperately), conduct an appropriate hypothesis test to determine if this proportion is greater than the 13.5%.  Clearly include and narrate each step.  

3) Describe **precisely and in context** what your p-values above indicate, using the definition of p-value (not just the number or the conclusion).

4) In each year 2015 and 2016, use your pivot table to compute the proportion of Americans killed by police who were **unarmed**.  Conduct an appropriate hypothesis test to see if the proportion in 2015 differs from the proportion in 2016.  Clearly show all steps and conclusions.

<br><br>



# HW 5 - The Normal Distribution 

## (Due Thurs Oct 29 by 10pm on Notebowl)

Turn in a Google Docs report, exported to pdf.  As usual, take care to make it presentable.  


Using the built-in functions in Google Sheets, compute the following probabilities.  Do *not* use a Z table -- software only.  <small>(But, if you know another statistical software platform/language and want to show off, you can use that too **as long as you clearly show the (written) commands you used.  No web apps.** ) </small>

For each, show **both** the command you used, and the output.

a) Women in Sweden have mean height 65.23 inches (stdev 2.64).  What percent of Swedish women are taller than 71"?

b)  Female giraffes have mean height 16.8' (stdev 1.7').  What's the probability that a randomly selected female giraffe is between 16' and 17' tall?

c)  The residuals for a linear regression model follow a normal distribution, with mean 0 units and stddev 0.73 units.  What's the range of the middle 80% of residuals for this model?

d) At a large state university, exam scores for a large lecture section of Calculus follow a normal distribution with mean 74% and stdev 8.2%.  How high must a student score in order to be at the 80th percentile?


e) At Denison, about 82% of students are from out-of-state (ie grew up outside of Ohio).  If we take a sample of 100 students, what's the likelihood that at least 75% of them are from out-of-state?


f) To relieve stress, Prof Miller sometimes completes "speedruns" (ie, as fast as possible) of the classic 1994 Nintendo adventure game, *Super Metroid*.  Her average completion time is 2 hours 32 minutes, stdev 24 minutes.  <small>*(She's probably done this nearly 100 times in the past 25 years.)*</small>
<br>If her completion times follow a normal distribution, what's the chance that her completion time on a random speedrun is more than 2 standard deviaitons (above or below) her average completion time.

<br><br>

# HW 4 - The Death Penalty

Due Friday Oct 16 by 5pm on Notebowl.  Submit .pdf report as usual.

In this HW, you'll answer some basic probability questions using the **Death Penalty Data** (see our shared folder on Google Drive for the data).

**For each answer, give the number answer first, followed by a brief explanation with a complete sentence or two.**

**To find the answers, you'll need to make an appropriate contingency table (ie a pivot table that shows counts)**  




1) Regarding the `Method` and `Region` variables, 
  - What's the probability that a randomly selected prisoner died by electrocution? 
  - What's the probability that a randomly selected prisoner was executed in the South?
  - What's the probability that a randomly selected prisoner was executed in the South and the method was Lethal Injection?
  


2)  Are the events "died by Electrocution" and "executed in the Northeast" mutually exclusive events?  Why or why not? Justification requires math.


3)  Are the events "executed in the Midwest" and "died by Lethal Injection" **independent**?  Why or why not? Justification requires math.


4)  If we know that a prisoner was executed in the South, what's the probability that they died in a Gas Chamber?

5)  What's the probability that a randomly selected prisoner was executed in the South or died by Firing Squad?

Late HW will not be accepted for any reason.  Students may turn in HW early, of course.


# HW 3 - The Titanic

Due Friday Oct 2 by 5pm on Notebowl.  Submit as .pdf document per the usual.

In this HW you'll be investigating a [dataset](https://drive.google.com/drive/folders/1tJFLMDFflBiXDHidWoTZU0SjzVi_z3zW?usp=sharing) that catalogs details about 890 passengers of the historic Titanic maiden voyage (about 1/3 of the total).

Your goal is to make the following pivot tables:

*(Remember, you can copy/paste your Google Sheets pivot tables into a Google Docs document)*

1) Make a pivot table to show **percentages** of passenger survival, broken down by `sex`.  *Hint: Choose `sex` for the rows.

2)  Make a pivot table showing the average age broken down by both `sex` and `Pclass` (passenger class, either 1, 2, or 3).

3)  Make a pivot table to check for outliers in `Fare` (ie, the price of the ticket) for each passenger class (`pclass`).  Your table should show outlier cutoffs, as well as min/max values for each class.

For each of the above pivot tables, write a sentence or two explaining the practical meaning of your findings.

Everything should be neatly and clearly presented in a Google Docs report in complete English sentences and paragraphs.  Exported to .pdf.  

Late HW will not be accepted for any reason.  Students may turn in HW early, of course.



# HW 2 - What's In Your Breakfast Cereal?

Due Friday Sept 18 by 5pm on Notebowl.  Submit as .pdf document, just like HW 1.

For this HW you'll be looking at data on a selection of common breakfast cereals.  [Find the data here](https://docs.google.com/spreadsheets/d/1bkgXy3AP8MBGS98_Qhb4Df9L2y0Mjw7YtepJC7H5-9w/edit?usp=sharing)

(For the record, I'm a Honey Bunches of Oats woman, myself.)

Your goal is to create and analyze linear models for the following:

- Predict `Fiber` based on `Potassium`
- Predict `Protein` based on `Sugar`.

For each, perform the following:

  1) Make a scatterplot, and describe its key features using language from lecture.
  2) Compute the 5 key summary statistics:
    $\bar{x}$, $\bar{y}$, $s_x$, $s_y$, $r$
  3) Compute the equation of the least-squares line.
  4) Carefully interpret the slope of the line, as practiced in lecture.
  4) Make, and interpret, a residual plot.
  5) Compute and interpret $R^2$.

Everything should be neatly and clearly presented in a Google Docs report in complete English sentences and paragraphs.  Exported to .pdf.  

Late HW will not be accepted for any reason.  Students may turn in HW early, of course.


# HW 1  - Investigating the Iris Data

Due Friday Sept 4 on Notebowl by 5pm as a **.pdf document.**

To watch me talk about this in video, view the **Week 2, Wednesday Aug 26** lecture video.  Remember, links to lecture vids are on my GitHub homepage millera2.github.io.

This dataset concerns the `iris` dataset that I've shared with you on Notebowl.

HW will be graded on completeness, correctness, and presentation (including the use of English sentences, good formatting, and overall clarity of the work).

Late HW will not be accepted for any reason.  Students may turn in HW early, of course.

## Problem 1 

By making histograms, find a variable in the dataset that seems the most **symmetric**.  Paste the histogram for this variable (just the symmetric one).

What measures of center and spread are appropriate for this variable?  Compute these directly, using appropriate commands in Google Sheets.  Show the commands you used, and your results, in your solution for Problem 1 (along with the histogram).


## Problem 2 

By making histograms, find a variable in the dataset that seems the most **skew**.  Paste the histogram for this variable (just the skew one).

What measures of center and spread are appropriate for this variable?  Compute these directly, using appropriate commands in Google Sheets.  Show the commands you used, and your results, in your solution for Problem 1 (along with the histogram).

## Problem 3

By using the sorting function of Google Sheets, find the mean Sepal Length for each species (*setosa*, *versicolor*, and *virginica*.).

