---
title: "Math 120 Lec 27"
author: "Ali Miller"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document:
    toc: true
    toc_depth: 3
    code_folding: show
    theme: simplex
    df_print: paged
  
  
---

```{r setup, include=FALSE}

#---------- RSTUDIO STARTER V 2.0  --------------#
#                    -Prepared with care by  AM ;D
                
                                                                          
knitr::opts_chunk$set(echo = TRUE, 
                      message = FALSE, 
                      warning = FALSE)      
library(tidyverse)                
library(ggthemes)                    

theme_set(theme_tufte() +                                     
  theme(text=element_text(family="sans")))  

#------------------------------------------------#
```







## Errors in Hyp Tests

There are two kinds.  Since mathematicians are clever, their names are:

- Type I Error  (False Positive)  It's when we reject H0 (positive), but we shouldn't have because H0 is true! (false positive)

- Type II Error (False Neg)  It's when we fail to reject H0 (negative), but we should have because H0 is false!!

The interesting part is what these mean practically.  

Example:  recall the problem about the faculty handbook.  I wanted to show that there's support for my proposal.

H0:  p = 2/3
Ha:  p > 2/3

What do the error types mean?

Type I:  I think that more than 2/3 of faculty support me, when in fact that's not the case.  I might be setting myself up for failure if I propose the change during the faculty meeting.


Type II:  I don't think I have enough support for the proposal, when in fact there is more than 2/3 support.  I might miss an opportunity to pass my successful proposal!

## Error Worksheet

#### #2  Criminal trial:

H0:  innocent
Ha:  guilty

Type I:  We think they're guilty, but actually they're innocent.  An innocent person goes to jail.
Type II: We think they're innocent, but actually they're guilty.  An guilty person  goes free!

Prof Miller:  I think type I is worse, I wouldn't want an innocent person (me!) to be punished.

Could argue:  what if the criminal in question is super dangerous?


#### #1  Water levels

H0: mu = .8
Ha: mu > .8  (preview for future)

Type I:  We think the water is dangerous, but actually it's safe.
Type II: We think the water is safe, but actually it's dangerous.

Prof Miller thinks that type II is worse, because then people would drink dangerous water!

In type I, we merely waste money cleaning water that's already safe.
















































