---
title: "Math 120 Lab 02 - Linear Regression"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document:
    toc: false
    toc_depth: 3
    code_folding: show
    theme: yeti
    df_print: paged
  
---

```{r setup, include=FALSE}
###########################################################################
################# DON'T DELETE THIS PART!!!!!##############################
###########################################################################
                                                                          #
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)      #
                                                                          #
library(tidyverse)           #The tidyverse has all of our data tools     #
library(ggthemes)            #ggthemes makes our graphs look nicer        #
                                                                          # 
theme_set(                                #this sets the theme for all    #
  theme_tufte() +                         #plots that we make             #
  theme(text=element_text(family="sans"))                                 #
  )                                                                       #
                                                                          #
                                                                          #
                                                                          #
### Below is where you read and store your data.                          #
                                                                          #
youShouldRenameThis <- read_csv("death penalty data.csv")
                                                                          #
                                                                          #
                                                                          #
############# ^ ################################# ^ #######################
############# | ## DON'T DELETE THIS PART!!!!!### | #######################
############# | ################################# | #######################
```



## Introduction

In this lab, we'll be using the techniques of linear regression to investigate the selling price of homes in King County, WA (the county that contains Seattle).  Our dataset has information about over 20,000 sold homes in the county, along with almost 20 variables about each house.

Your goal:  build a single-variable linear model to predict the **price** at which a house sells.  You'll justify why yours is a good model, and you'll also compare it to at least one other model.  **There are many explanatory variables to choose from, but all of you will use *price* as the response variable (y)**.

## The dataset

[You can download the data here.](https://millera2.github.io/Data/House-Sales.csv)  Most of the variables in the dataset (`House-Sales.csv`) have easy-to-understand column names, but here's a codebook:


- **id** A notation for a house
- **date** Date house was sold
- **price** Sale price
- **bedrooms**  Number of Bedrooms/House
- **bathrooms** Number of bathrooms/House
- **sqft_living** square footage of the home
- **sqft_lot** square footage of the lot
- **improvements** [I'm not sure what exactly this one means!]
- **floorsTotal**  floors (levels) in house
- **waterfrontHouse**  which has a view to a waterfront
- **view** Has been viewed
- **hoa** Is part of a Homeowner association
- **condition** How good the condition is ( Overall )
- **gradeoverall**  grade given to the housing unit, based on King County grading system
- **sqft_above** square  footage of house apart from basement
- **sqft_basement** square  footage of the basement
- **yr_builtBuilt** Year
- **yr_renovated** Year when house was renovated
- **zipcode** zip
- **lat** Latitude coordinate
- **long** Longitude coordinate
- **sqft_living15** Living room area in 2015(implies-- some renovations) This might or might not have affected the lotsize area
- **sqft_lot15** lotSize area in 2015(implies-- some renovations)

[All descriptions taken from Kaggle.com.](https://www.kaggle.com/harlfoxem/housesalesprediction)

## The Exploratory Phase

You guys have already had some experience exploring datasets.  This time, you'll be using lin regs for analysis.

**Your ultimate goal** is to find the best linear model to predict sale price.  Which variable gives us the best predictions?  Which one gives us the best model?

You should try many different explnatory variables.  Maybe the year the house was built?  Maybe the square footage of the lot?  Maybe the number of floors, or bathrooms have the biggest impact?  **It's up to you to decide!**  The only way you'll know what's best is by **trying out different models** and looking at your results.  Use the tools you've learned about in class to inform your decision!

## Deliverables

The format is the same as last time:  turn in your .Rmd and .html files.  500 word count limit.  I think that 500 will feel very short; **be judicious about including only the most important info!**

In this one, you'll almost certainly need more than 2 graphs.  Let's say, **no more than 6 graphs**.  

Your report should include:

- Relevant observations about the distribution for sale price.
- The equation for your final model.  Ask how to make it look pretty like this:  

$$\hat{y}=b_1 x+b_0$$

- A clear explanation of the coefficients.
- A thorough analysis of the residuals.
- A discussion about $r$, $r^2$, and what they mean.
- A discussion about possible outliers/influential values.
- A brief discussion of one other model you tried, and why your final model is the best.

Your target audience is someone who's in the housing markets matter the most when determining value in this market?

## Deadline and Grading

This lab is due **Friday, Sept 20th at 4:59pm**.  Your client needs to make a decision soon, so the deadline is critical here.  **I'll charge a 20% late fee per day late.**  

I will assign grades on this project ”holistically”, not using a scoring sheet where each item is worth a certain number of points.

- **B**: A ”B” project is very well done. It should have sound analysis, use appropriate statistical tools, support analysis with the appropriate graphs and other visual aids, and be a well-written document.

- **C**: A ”C” project is solid, but usually lacking in one of the areas listed above. 

- **D/F**: Projects below a C are severely deficient in the basic criteria or have failed to complete the assignment.

- **A**: An ”A” project is truly above ordinary; it has exceptional qualities that make it stand out distinctly. An ”A” project is not the default grade.
  - Does the project fulfill the requirements of the assignment?
  - Does this report have a ”thesis” or ”story” that is the focus? Does the rest of the report support the thesis?
  - Does the report use the subject matter from this unit appropriately? Are there tools being used in the wrong way? Is there an obvious tool that might have been used but was overlooked?
  - Are the graphics factually correct? Are they formatted well? Do they give the first visual impression that is supportive of the thesis/story of the report, or do they indicate a different story?
  - Is the report well-written? Is there good organization of ideas? Is the story/thesis communicated clearly? Is the analysis grounded in reasonable use of statis- tics? Is the paper free of mechanical and grammatical errors?
  - Does the report provide the right context for the target audience? Is the right information provided? Have the right assumptions been made about what the audience knows or does not know?
