---
title: "Math 120 HW"
author: "Your Name"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document:
    toc: true
    toc_depth: 1
    code_folding: show
    theme: yeti
    df_print: paged
  
  
---

```{r setup, include=FALSE}

#---------- RSTUDIO STARTER V 2.0  --------------#
#                    -Prepared with care by  AM ;D
                
                                                                          
knitr::opts_chunk$set(echo = TRUE, 
                      message = FALSE, 
                      warning = FALSE)      
library(tidyverse)                
library(ggthemes)                    

theme_set(theme_tufte() +                                     
  theme(text=element_text(family="sans")))  

#------------------------------------------------#
```

# HW 2 - What's In Your Breakfast Cereal?

Due Friday March 12 by before the beginning of class.  Submit as .pdf document, just like HW 1.

For this HW you'll be looking at data on a selection of common breakfast cereals.  [Find the data here](https://docs.google.com/spreadsheets/d/1bkgXy3AP8MBGS98_Qhb4Df9L2y0Mjw7YtepJC7H5-9w/edit?usp=sharing)

(For the record, I'm a Honey Bunches of Oats woman, myself.)

Your goal is to create and analyze linear models for the following:

- Predict `Fiber` based on `Potassium`
- Predict `Protein` based on `Sugar`.

For each, perform the following:

  1) Make a scatterplot, and describe its key features using language from lecture.
  2) Compute the 5 key summary statistics:
    $\bar{x}$, $\bar{y}$, $s_x$, $s_y$, $r$
  3) Compute the equation of the least-squares line.
  4) Carefully interpret the slope of the line, as practiced in lecture.
  4) Make, and interpret, a residual plot.
  5) Compute and interpret $R^2$.

Everything should be neatly and clearly presented in a Google Docs report in complete English sentences and paragraphs.  Exported to .pdf.  

Late HW will not be accepted for any reason.  Students may turn in HW early, of course.



# HW 1  - Investigating the Iris Data

Due Friday Feb 26 on Notebowl before the beginning of class as a **.pdf document.**


This dataset concerns the `iris` dataset that I've shared with you on [Google Drive](https://drive.google.com/drive/folders/1iTP3k6vpQrV1moJAR3XQrFd4U-c6J3GZ?usp=sharing) (you can click the link here).

HW will be graded on completeness, correctness, and presentation (including the use of English sentences, good formatting, and overall clarity of the work).

**Late HW will not be accepted for any reason.**  Students may turn in HW early, of course.

## Problem 1 

By making histograms, find a variable in the dataset that seems the most **symmetric**.  Paste the histogram for this variable (just the symmetric one).

What measures of center and spread are appropriate for this variable?  Compute these directly, using appropriate commands in Google Sheets.  Show the commands you used, and your results, in your solution for Problem 1 (along with the histogram).


## Problem 2 

By making histograms, find a variable in the dataset that seems the most **skew**.  Paste the histogram for this variable (just the skew one).

What measures of center and spread are appropriate for this variable?  Compute these directly, using appropriate commands in Google Sheets.  Show the commands you used, and your results, in your solution for Problem 1 (along with the histogram).

## Problem 3

By using the sorting function of Google Sheets, find the mean Sepal Length for each species (*setosa*, *versicolor*, and *virginica*.).

