---
title: "Math 120 HW"
author: "Your Name"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document:
    toc: true
    toc_depth: 1
    code_folding: show
    theme: yeti
    df_print: paged
  
  
---

```{r setup, include=FALSE}

#---------- RSTUDIO STARTER V 2.0  --------------#
#                    -Prepared with care by  AM ;D
                
                                                                          
knitr::opts_chunk$set(echo = TRUE, 
                      message = FALSE, 
                      warning = FALSE)      
library(tidyverse)                
library(ggthemes)                    

theme_set(theme_tufte() +                                     
  theme(text=element_text(family="sans")))  

#------------------------------------------------#
```

# HW 5 - The Normal Distribution 

Due:  **Fri Nov 18 on Notebowl before class time.**

Turn in a Google Docs report, exported to pdf.  As usual, take care to make it presentable.  


**Using the built-in functions in Google Sheets**, compute the following probabilities.  Do *not* use a Z table -- software only.  <small>(But, if you know another statistical software platform/language and want to show off, you can use that too **as long as you clearly show the (written) commands you used.  No web apps.** ) </small>

For each, show **both** the command you used, and the output.

a) Women in Sweden have mean height 65.23 inches (stdev 2.64), and their heights follow a normal dist.  What percent of Swedish women are taller than 71"?

b)  Female giraffes have mean height 16.8' (stdev 1.7').  What's the probability that a randomly selected female giraffe is between 16' and 17' tall?



c) At a large state university, exam scores for a large lecture section of Calculus follow a normal distribution with mean 74% and stdev 8.2%.  How high must a student score in order to be at the 80th percentile?


d) At Denison, about 82% of students are from out-of-state (ie grew up outside of Ohio).  If we take a sample of 100 students, what's the likelihood that at least 75% of them are from out-of-state?


e) Suppose we wish to construct a 60% CI for a population mean (mu), based on a sample of size n=33.  Use Google Sheets to find the exact critical value we'd use, to four decimal places.

f)  Suppose we want to construct a 75% CI for a population proportion.  Find the exact critical value, to four decimal places.

<br><br><br>

# HW 4 - The Death Penalty

Due Friday Nov 5 before the beginning of class time.  Submit .pdf report as usual.

In this HW, you'll answer some basic probability questions using the **Death Penalty Data** (see our shared folder on Google Drive for the data).  This dataset contains info on every person to receive the death penalty in modern times, following the 1976 US Supreme Court decision that made it legal.

**For each answer, give the number answer first, followed by a brief explanation with a complete sentence or two.**

**To find the answers, you'll need to make an appropriate contingency table (ie a pivot table that shows counts)**  




1) Regarding the `Method` and `Region` variables, 
  - What's the probability that a randomly selected prisoner died by electrocution? 
  - What's the probability that a randomly selected prisoner was executed in the South?
  - What's the probability that a randomly selected prisoner was executed in the South and the method was Lethal Injection?
  


2)  Are the events "died by Electrocution" and "executed in the Northeast" mutually exclusive events?  Why or why not? Justification requires math.


3)  Are the events "executed in the Midwest" and "died by Lethal Injection" **independent**?  Why or why not? Justification requires math.


4)  If we know that a prisoner was executed in the South, what's the probability that they died in a Gas Chamber?

5)  What's the probability that a randomly selected prisoner was executed in the South or died by Firing Squad?

Late HW will not be accepted for any reason.  Students may turn in HW early, of course.

# HW 3 - The Titanic

Due Friday October 15 on Notebowl before class time.  Submit as .pdf document per the usual.

In this HW you'll be investigating a [dataset](https://drive.google.com/drive/folders/1C1XHN3PGe4lMQXS_hq49btBM6QaiEuBW?usp=sharing) that catalogs details about 890 passengers of the historic Titanic maiden voyage (about 1/3 of the total).

Your goal is to make the following pivot tables:

*(Remember, you can copy/paste your Google Sheets pivot tables into a Google Docs document)*

1) Make a pivot table to show **percentages** of passenger survival, broken down by `sex`.  *Hint: Choose `sex` for the rows.

2)  Make a pivot table showing the average age broken down by both `sex` and `Pclass` (passenger class, either 1, 2, or 3).

3)  Make a pivot table to check for outliers in `Fare` (ie, the price of the ticket) for each passenger class (`pclass`).  Your table should show outlier cutoffs, as well as min/max values for each class.

For each of the above pivot tables, write a sentence or two explaining the practical meaning of your findings.

Everything should be neatly and clearly presented in a Google Docs report in complete English sentences and paragraphs.  Exported to .pdf.  

Late HW will not be accepted for any reason.  Students may turn in HW early, of course.


# HW 2 - What's In Your Breakfast Cereal?

Due Friday Oct 1 before the beginning of class.  Submit as .pdf document, just like HW 1.

For this HW you'll be looking at data on a selection of common breakfast cereals.  Find the data on our [shared Google Drive folder](https://drive.google.com/drive/folders/1C1XHN3PGe4lMQXS_hq49btBM6QaiEuBW?usp=sharing) (you can click the link here).

(For the record, I'm a Honey Bunches of Oats woman, myself.)

Your goal is to create and analyze linear models for the following:

- Predict `Fiber` based on `Potassium`
- Predict `Protein` based on `Sugar`.

For each, perform the following:

  1) Make a scatterplot, and describe its key features using language from lecture.
  2) Compute the 5 key summary statistics:
    $\bar{x}$, $\bar{y}$, $s_x$, $s_y$, $r$
  3) Compute the equation of the least-squares line.
  4) Carefully interpret the slope of the line, as practiced in lecture.
  4) Make, and interpret, a residual plot.
  5) Compute and interpret $R^2$.

Everything should be neatly and clearly presented in a Google Docs report in complete English sentences and paragraphs.  Exported to .pdf.  

Late HW will not be accepted for any reason.  Students may turn in HW early, of course.



# HW 1  - Investigating the Iris Data

Due Friday Sept 17 on Notebowl before the beginning of class as a **.pdf document.**


This dataset concerns the `iris` dataset that I've shared with you on [Google Drive](https://drive.google.com/drive/folders/1C1XHN3PGe4lMQXS_hq49btBM6QaiEuBW?usp=sharing) (you can click the link here).

HW will be graded on completeness, correctness, and presentation (including the use of English sentences, good formatting, and overall clarity of the work).

**Late HW will not be accepted for any reason.**  Students may turn in HW early, of course.

## Problem 1 

By making histograms, find a variable in the dataset that seems the most **symmetric**.  Paste the histogram for this variable (just the symmetric one).

What measures of center and spread are appropriate for this variable?  Compute these directly, using appropriate commands in Google Sheets.  Show the commands you used, and your results, in your solution for Problem 1 (along with the histogram).


## Problem 2 

By making histograms, find a variable in the dataset that seems the most **skew**.  Paste the histogram for this variable (just the skew one).

What measures of center and spread are appropriate for this variable?  Compute these directly, using appropriate commands in Google Sheets.  Show the commands you used, and your results, in your solution for Problem 1 (along with the histogram).

## Problem 3

By using the sorting function of Google Sheets, find the mean Sepal Length for each species (*setosa*, *versicolor*, and *virginica*.).

