
---
title: "Math 120 Fall 2020 Homepage"
date: "Updated: `r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document:
    toc: true
    toc_depth: 2
    theme: yeti

      
  
---

```{r setup, include=FALSE}

                                                                          #
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)      #
                                                                          #
library(tidyverse)           #The tidyverse has all of our data tools     #
library(ggthemes)            #ggthemes makes our graphs look nicer        #
                                                                          # 
theme_set(                                #this sets the theme for all    #
  theme_tufte() +                         #plots that we make             #
  theme(text=element_text(family="sans")) + 
  theme(axis.text.x = element_text(angle=-90))                            #
  )                                                                       #
                                                                          #
                                                                          #
                                                                          #

```

## Math 120 Partial Lecture Notes
*They look great on your phone, so you can read them anywhere.    Don't understand something?  Ask me!*

- [Week 1](https://millera2.github.io/Math-120-C/Math-120-Lec-01.html)
- [Week 2](https://millera2.github.io/Math-120-C/Math-120-Lec-02.html)
- [Week 3](https://millera2.github.io/Math-120-C/Math-120-Lec-03.html)
- [Week 4](https://millera2.github.io/Math-120-C/Math-120-Lec-04.html)
- [Week 5](https://millera2.github.io/Math-120-C/Math-120-Lec-05.html)
- [Week 6](https://millera2.github.io/Math-120-C/Math-120-Lec-06.html)
- [Week 8](https://millera2.github.io/Math-120-C/Math-120-Lec-07.html)
- [Week 9](https://millera2.github.io/Math-120-C/Math-120-Lec-07.html)

## Next Quiz

Sampling distributions for xbar and phat.

Practice problems:

1)  The average wait time at a particular bus stop is 12 min, with stdev 2.1 min.  If we take a sample of 35 people, what's the probability that their mean wait time is at least 10 min?

2)  The average wait time at a particular bus stop is 12 min, with stdev 2.1 min.  If we take a sample of 50 people, how high must their average wait time be in order to be in the top 5% of sample mean wait times?

3)  This year at DU, 51% of students are female.  In a sample of 45 students, what's the probability that at least half of them are female?

<small> Answers:

1) 0.9205  2) 12.49   3) 0.5534

</small>

<br><br>


## HW Assignments

[Click here for HW Assignments](https://millera2.github.io/Math-120-C/HW.html)



## Office Hours 

### Prof Miller's Hours (Google Meet)

Zoom Room:  [https://zoom.us/j/96985430147?pwd=K2tMSlhCVFZ3NmZXenhybGtqZFA4QT09](https://zoom.us/j/96985430147?pwd=K2tMSlhCVFZ3NmZXenhybGtqZFA4QT09)

Passcode (if needed): i7GYcC

All virtual, all by appointment.  Don't be shy!  A few things:

- Schedule 24 hours in advance
- I'm free most weekdays from 1:30-4pm
- When you write, propose a time to cut down on back-and-forth.

I never check email after 4pm, so **don't wait till the night before a deadline to get help!**  

I like chatting with students -- come find me!



## TA Hours

Our TA, Pede, will hold hours on Google Meet (he uses his own [Google Meet Room, click here](https://meet.google.com/gjf-ecsw-ysd?hs=151) ) at the following times:

- Thursday 12-2pm
- Sunday 6pm-9pm








## Shared Google Drive Folder:

[Click here to visit our shared drive.](https://drive.google.com/drive/folders/1iTP3k6vpQrV1moJAR3XQrFd4U-c6J3GZ?usp=sharing)


## Texbook Links

- [Math 120 Textbook](https://www.openintro.org/book/os/)
  - *OpenIntro Statistics* is an excellent, free introduction to modern statistical analysis.
  

