
---
title: "CS 111 Fall 2020 Homepage"
date: "Updated: `r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document:
    toc: true
    toc_depth: 3
    theme: yeti

      
  
---

```{r setup, include=FALSE}

                                                                          #
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)      #
                                                                          #
library(tidyverse)           #The tidyverse has all of our data tools     #
library(ggthemes)            #ggthemes makes our graphs look nicer        #
                                                                          # 
theme_set(                                #this sets the theme for all    #
  theme_tufte() +                         #plots that we make             #
  theme(text=element_text(family="sans")) + 
  theme(axis.text.x = element_text(angle=-90))                            #
  )                                                                       #
                                                                          #
                                                                          #
                                                                          #

```


## Video Lectures

These are all on [our shared folder on Google](https://drive.google.com/drive/folders/1ttByiga1W9uSIpLj9KSzFTDSzWaGwm8F?usp=sharing)

The work I do in those vids is availabe on this site below.  


## CS 111 Lecture Notes
*They look great on your phone, so you can read them anywhere.  Steal my code!  Don't understand something?  Ask me!*


- [Week 1](https://millera2.github.io/CS-111/Lec-01.html)
- [Week 2](https://millera2.github.io/CS-111/Lec-02.html)
- [Week 3](https://millera2.github.io/CS-111/Lec-03.html)

## Next Quiz: Sept 09

Lecture Coverage:  Week 3

Book coverage: Section 2.1-2.4

Key Skills:  Arithmetic in python, floor and mod functions, handling data types, converting between strings and integers, using the `input()` function.



## HW Assignments

HW 2 is up!


[Here are the HW Assignment Descriptions](https://millera2.github.io/CS-111/HW.html)

  

## Reading Assignments

Wanna know what's going on?  Read this stuff!

- Due 8/19: Textbook 1.1 and 1.2 (p1-10)

- Due 8/21: Texbtook 1.3 (p11-19)

- Due 8/28: Textbook 1.4 (p20)
  
## Syllabus

[Math 120 Fall 2020 Syllabus (Miller)](https://millera2.github.io/CS-111/CS-111-Fall2020-Miller.pdf)

## Office Hours 

### Prof Miller's Hours (Google Meet)

Google Meet Link: https://meet.google.com/taw-tooc-twh

Hours: Most weekdays before 4pm.

If you want to talk, shoot me an email (always use Denison email addresses) and propose a couple of times that work for you.

Of course, I don't check email in the evening, so we'll have to meet the next day in that case.

So, **don't wait till the night before a deadline to get help!**  

I like chatting with students -- come find me!

I think this will be better than setting aside specific times that work for everyone.




### TA Hours

*TBA*


## Helpful Links and Info:



### Datasets

Wanna check out a dataset referenced in lecture or HW?  Here they are!  I'll add more as the semester progresses. 

- [Baby Names](https://drive.google.com/file/d/1W5baem_xOJ9SVlaD_QHnXNdfA9dtBXaS/view?usp=sharing)
  - *Counts of **all** American first names since 18-something.*
- [Death Penalty](https://millera2.github.io/Data/death-penalty-data.csv)
  - *Records of every American who's received capital punishment.*
- [CIRP DATASET](https://drive.google.com/file/d/1-FxOfb3-Hm8DPKSpkqlHGZ91154xMW4s/view?usp=sharing)
  - *DU Freshmen Survey Data from 2014.  Not public data.*

for Reading Assignments and Labs)*


