---
title: "CS 111 HW"
date: "Updated `r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document:
    toc: true
    toc_depth: 3
    code_folding: show
    theme: yeti
    df_print: paged
  
  
---

```{r setup, include=FALSE}

#---------- RSTUDIO STARTER V 2.0  --------------#
#                    -Prepared with care by  AM ;D
                
                                                                          
knitr::opts_chunk$set(echo = TRUE, 
                      message = FALSE, 
                      warning = FALSE)      
library(tidyverse)                
library(ggthemes)                    

theme_set(theme_tufte() +                                     
  theme(text=element_text(family="sans")))  

#------------------------------------------------#
```

# Grading Guidelines For Homework

Homework solutions will be graded on the following critera:

- Quality and thoughtfulness of presentation.  Use of gramatically correct English sentences (when writing English). 
- Completion and accuracy of solutions.
- Ingenuity and elegance.
- Relevance to the topic(s) at hand.
- Demonstration of the student's understanding of the material.
- Creativity, ingenuity, and elegance demonstrated in a student's ideas and insights.


# HW 2 Due Friday 9/11 by 5pm

File Format: turn in the .ipynb file for your notebook.  Name it with this format:

Lastname_Firstname_HW3.ipynb

So, if I was a student, I'd turn in:

Miller_Alice_HW3.ipynb

Problems:

1) 2.2.7
2) 2.2.8
3) 2.3.4

4)  In class on Friday Sept 04, we wrote a `for` loop to assign each employee in a list of employees a day of the week to work on.

- Your HW problem is to extend this program in the following way:

  - It should prompt the user (who we'll call "The Boss") to enter the list of employees, and the list of days in the week that the business is open.  This list can be arbitraily long, depending on what the user inputs. You may assume that all of the names are different.  Use the `input()` function.  There are many reasonable ways to go about this.  
  - It should prompt the user for the list of days that the business is open.  You may assume that this list will be some subset of "Mon", "Tues", "Wed", "Thurs", "Fri", "Sat", "Sun". 

- There are two acceptable outputs:

  1)  Your program can print out the schedule in the same way we did in Lecture.  A correct solution like this will earn a maximum of 92% credit for this problem.

  2)  Your program can return a list of lists (one for each day of the work week) that show who works on which day.  
      - For example, if the work week consists of Mon, Tue, Wed, Thurs, Fri, and the employee list is Ali, Ben, Charles, Deb, Ellie, Fred, Greg, Helen, Ian, Jack, then the output should be the followign list of lists:

`[['Ali, Fred'], ['Ben', 'Greg'], ['Charles', 'Helen'], ['Deb', 'Ian'], ['Ellie', 'Jack']]`


# HW 1 Due Friday 8/28 by 5pm

File format: Problems should be completed in a Jupyter Labs notebook, exported to html (we'll talk about this in class).  The .html file should be submitted to NoteBowl under the HW 1 assignment.

Each solution should be written in a seperate Markdown cell, showing the problem number with a header (you can make a header by starting the line with "#").

The first cell of the notebook should have a header for the title of the assignment (CS 111 HW 1), and your name.

The problems for this HW come from the text:

- 1.2.1
- 1.2.2
- 1.2.5
- 1.3.1


All of these problems should be solved in clear, consise English sentences (or lists).  No code here.