
---
title: "Math 220 Spring 2023 Homepage"
date: "Updated: `r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document:
    toc: true
    toc_depth: 3
    theme: yeti

      
  
---

```{r setup, include=FALSE}

                                                                          #
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)      #
                                                                          #
library(tidyverse)           #The tidyverse has all of our data tools     #
library(ggthemes)            #ggthemes makes our graphs look nicer        #
                                                                          # 
theme_set(                                #this sets the theme for all    #
  theme_tufte() +                         #plots that we make             #
  theme(text=element_text(family="sans")) + 
  theme(axis.text.x = element_text(angle=-90))                            #
  )                                                                       #
                                                                          #
                                                                          #
                                                                          #

```





## Lecture Notes

These look great on your phone - easy to study on the go!

[Click here for notes](http://millera2.github.io/Math-220-S23/Math220Lec.html)


## Exam Solutions

[Click here for Shared Folder](https://drive.google.com/drive/folders/1PGihqyMH9GodiehPoyenu8wi1CF0ytOf?usp=share_link)


## Homework

- For full **credit**, write neatly and be sure to **staple/print/prepare your work before** class.
- Be sure your physical (handwritten/printed) HW is in the pile before I take attendance at the beginning of class.  
- <b><big>Once attendance begins, I will no longer accept HW. </b></big>  
- I drop 2 low scores, in case of an emergency.

### HW Week 11 (Due Monday April 17)

Reading:  9.2 (2 means), 9.4 (2 proportions), 12.1 (lin reg)

Practice Problems:

- 9.2  19-23odd
- 9.4  51, 53

**Even problems due to turn in:**

- 9.2  #18, 20 (p379)
- 9.4  #50 (**part a only**), 52 (p397)
- 12.1. #2

<br><br>

### HW Week 10 - Final Project Proposal

This week is a little different.  You (and your team) will submit a proposal for the final project.  It should contain:

- A clear list of everyone on the team.  
  - **You must commit to a team now.**
  - All team-mates **must be in the same section of 220**.
- The dataset(s) you plan to use for the project.  A few guidelines:
  - Must be **rectangular** data.  Refer to our Week 1 notes.
  - Must be **real** data.  No simulations or "experimental" datasets.  Observations must have come from actual, real-life sources.
- One paragraph describing your ideas for the project.  The paragraph must contain:
  - Where the data came from.  Recorded when, where, by who?
  - Why you're interested in the data.
  - Two questions that you believe you can answer with the dataset.
- **One visualization** from the data.  Examples:  histogram, barplot, scatterplot, qqplot, etc etc.

This doesn't need to be a book - your proposal should fit on one page.  **Two page maximum length.**

Export to pdf, and submit to our Canvas page.  Submissions are due **Friday, March 7, by 8am**.



<br>

### Exam II 

Reading: 8.1-8.4

Practice Problems:

- 8.29-39odd (p345)
- 8.42 (p350)
- 8.43-49 odd

For Friday: Google around for a dataset that interests you.  Load it into R, like we practiced in class.  Play around with it.  Anything interesting?

**The example code from class is in the Lecture Notes here on the site.  Also, see the Data Resources below for inspiration.**

### HW Week 8 (Due Fri Mar 24)

Reading:  7.1-7.4

Odds for Practice:  7.13-19odd,

**Even problems due to turn in:**

- 7.14 (p293)
- 7.16
- 7.18
- 7.20


### HW Week 7 (Due Fri Mar 10)

Reading: 6.1-6.2, 7.1-7.2

Odds for Practice:  6.1-6.9odd, 6.29, 7.1-7.7odd

**Even problems due to turn in:**

- 6.2 (p261) 
- 6.10 
- 6.22 (p273)
- 6.23 (credit only for full details in calculations)
- 6.24 (hint:  the pdf is very similar to the geometric distribution)
- 7.4 (p285)



### HW Week 6 (Due Fri Mar 3)

Reading: 4.4, 4.6, 5.3, 5.4

Odds for practice:  4.59-63odd, 4.87-93odd, 5.41, 5.47-55odd

**Even problems due to turn in:**

- 4.60 (p175)
- 4.62
- 4.94 (p193)
- 5.38 (p229)
- 5.40
- 5.48 (p237)
- 5.50


### HW Week 5 (Due Fri Feb 25)

Reading: 4.3,4.4

Odds for Practice:  4.29-35odd, 39, 53, 55

**Even problems due to turn in:**

- 4.28 (p167)
- 4.30
- 4.32
- 4.36
- 4.38
- 4.44
- 4.54


### Exam I

Reading:  3.3-3.6, 4.1-4.2

Practice:  

- 3.39 , 3.47 , 3.85, 4.5, 4.11, 4.13, 4.15
- 3.32 
- 3.56 
- 3.86
- 3.52 
- 3.82 
- 4.2 
- 4.6
- 4.14 
- 4.22

### HW Week 3 (Due Fri Feb 10)

Reading:  2.4, 2.5, 3.1, 3.2 

Examples from Reading:  3.7, 3.9, 3.10, 3.12, 3.22, 

Odds: 2.51, 2.71, 3.13, 3.39 

 

**Even problems due to turn in:** 

- 2.48 (p83)
- 2.52 
- 2.60
- 2.64 
- 2.74 (p89)
- 2.80
- 3.14 (p107)
- 3.22 



### HW Week 2 (Due Friday Feb 3)

Examples from Reading (Sec 2.1-2.3) : 2.7, 2.10, 2.14, 2.16, 2.22, 2.23

Odds: 2.3, 2.9, 2.13, 2.21, 2.25, 2.31, 

**Even problems due to turn in:** 

- 2.6 (p57) 
- 2.14 (p65)
- 2.26 
- 2.30 (p73)
- 2.32 
- 2.34 


### HW Week 1 (Due Friday Jan 27)

Reading: All of chapter 1.  Some HW problems refer to conepts in the reading.

Practice Odds: 1.17, 1.39, 1.49 *[Solutions in the back of the book!]

**Evens to turn in:  $\leftarrow$ [The important part!]**  

- 1.38, p35
- 1.42, p36
- 1.44, p44
- 1.56, p46
- 1.24, p27 [You may use R for help, sketch your result on paper.  Example below.  Don't forget the Tao of the histogram.]



<br><br>

## Old Homework Solutions

[Click Here For HW Solutions](https://millera2.github.io/Math-220-S23/Math220HW.html)



<br><br>


## How To Get Started On The Final Project

Big idea:  Pose two questions that you can answer with you dataset.  Do so using tools and methods from the class.  Present and write about your results.

1) Read the Final Project Instructions below.  
  - In particular, read the link on [How to Create a Research Poster](https://guides.nyu.edu/posters)
2) **Play**!  Have some fun messing around with your data.  Here are some things to try:
  - Visualizations:  make histograms, boxplots, scatterplots, qqplots, barplots, etc.  **For example code, scan through our class notes online!**
  - Statistical methods:  Summary stats, confidence intervals and hypothesis tests for   $\mu, p, \mu_1 -\mu_2, p_1-p_2$, linear models, ANOVA.
3) Come up with questions.  Can you compare groups?  Estimate a parameter?  Explore a possible linear relationship?  
4) Organize and polish your work.  Make graphs look nice.  Write up complete explanations/interpretations for the methods you used.  What assumptions/conditions?  What conclusions?
5) Organize your best stuff into a research poster.  Again, check link above for example.
6) Catalog all of this in your final paper.  You can copy/paste from R into Word or other software you like.  Or, you can do it all in RStudio if you've done so in DA.

<br>

## Grading Guidelines for Final Project

### Presentation/Poster

- Is poster well organized/well presented?  Clean/neat/good grammar/etc.
- Informational content:  does poster clearly show results and summary of analysis?  Make some cool visualizations, and explain them!
- Does the poster demonstrate knowledge of course methods?  Depth of understanding?
- Visually appealing?  Interesting presentations/questions?
- **Time/Duration**:  at least 6 minutes, no more than 7 minutes.  **Practice!**
- All group members spend **equal time presenting**.  Practice!

### Final Paper

- Length:  at least 1000 words (not including figures), no more than 2500 words.  **Longer is not better**; you don't have to write a book!
- **Most important**:  Demonstrate understanding/mastery of concepts from course.
- Read [Guide For Statistical Writing](https://millera2.github.io/Math-220-S23/statistical-report-writing.pdf)
- **Clearly show which group members contributed which text.**  Should be balanced among all!

<br>

## Final Project

### Project Description and Deadlines

[Click here for Final Project info](https://millera2.github.io/Math-220-S23/Final.html)

### Guide For Statistical Report Writing

[Click here for pdf](https://millera2.github.io/Math-220-S23/statistical-report-writing.pdf)

### Data Sources

You can choose (or collect!) your own data.  

Two favorites of mine:

- [Kaggle.com](https://www.kaggle.com)
- [data.world](https://data.world)

Both have active communities and trending datasets.  Easy to take a look and see what's out there.

Here are a couple lists of other sources to check out:

- [Denison Libraries Links (very good!)](https://libguides.denison.edu/statistics/finding_datasets)
- [Code Camp](https://www.freecodecamp.org/news/https-medium-freecodecamp-org-best-free-open-data-sources-anyone-can-use-a65b514b0f2d/)


<br><br>

## Office Hours 

I'm in Fellows 212.  I'll be there and available at:  

- Mon:  2:30-4pm
- Tues: 9-10:30am, 
- Wed:  2-4pm  


<br><br><br><br>
<br><br><br><br>

